apiVersion: apps/v1
kind: Deployment
# Deployment name
metadata:
  name: frontend-app-deployment
  labels:
    app: frontend-app
# Deployment specification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    # Pod specification
    spec:
      containers:
        - name: frontend-app
          image: adhouma/kubernetes-networking-frontend-app:latest
          env:
            - name: TASK_API
              value: "task-api-service.default"

# Run this deployment with
# kubectl apply -f ./deploy/frontend-app-deployment.yml

# If you make changes, just retag your image and push it to dockerhub ... then restart your deployment to see the changes you made with
# kubectl rollout restart deployment/frontend-app-deployment