apiVersion: apps/v1
kind: Deployment
# Deployment name
metadata:
  name: task-api-deployment
  labels:
    app: task-api
# Deployment specification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    # Pod specification
    spec:
      containers:
        - name: task-api
          image: adhouma/kubernetes-networking-task-api-app:latest
          volumeMounts:
            - mountPath: /app/tasks
              name: task-volume
          # First approach
          # Use the kubernetes DNS for communication between pods just like docker you can use the service name
          # in our case it's the auth-api-service than "." than the namespace used, in our case it's the default
          # Use kubectl get namespace to see all the namespaces
          # Now we can use auth-api-service.default as DNS in our user-app.js
          # Or you can use 

          # Second approach
          # Use environment variable auto generated by kubernetes when you apply your service.yml file for example the auth-api-service
          # The environment variable must be the name of the service all caps with "-" replaced by "_" and add SERVICE_HOST at the end
          # exactly like AUTH_API_SERVICE_SERVICE_HOST

          # We used both approachs in user-app.js file and in the tasks-app.js we will go with the first approach
          env:
            - name: AUTH_API
              value: "auth-api-service.default"
            - name: TASKS_FOLDER
              value: "tasks"
      volumes:
        - name: task-volume
          emptyDir: {}


# Run this deployment with
# kubectl apply -f ./deploy/task-api-deployment.yml

# If you make changes, just retag your image and push it to dockerhub ... then restart your deployment to see the changes you made with
# kubectl rollout restart deployment/task-api-deployment 