apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-persistent-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
    type: DirectoryOrCreate


# First you create a hostPath PersistentVolume. Kubernetes supports hostPath for development and testing on a single-node cluster. 
# A hostPath PersistentVolume uses a file or directory on the Node to emulate network-attached storage.

# In a production cluster, you would not use hostPath. 
# Instead a cluster administrator would provision a network resource like a Google Compute Engine persistent disk, 
# an NFS share, or an Amazon Elastic Block Store volume. 