apiVersion: v1
kind: Service
metadata:
  name: story-service
spec:
  selector:
    app: story
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer


# Run this service with
# kubectl apply -f ./deploy/service.yml

# Expose the service in your machine http://127.0.0.1:62545 for example using this command
# minikube service story-service