const express = require('express');
const bodyParser = require('body-parser');
const axios = require('axios');

const app = express();

app.use(bodyParser.json());

app.post('/signup', async (req, res) => {
  // It's just a dummy service - we don't really care for the email
  const email = req.body.email;
  const password = req.body.password;

  if (!password || password.trim().length === 0 || !email || email.trim().length === 0) {
    return res
      .status(422)
      .json({ message: 'An email and password needs to be specified!' });
  }

  try {
    /* ---- First approach ---*/
    // Use the kubernetes DNS for communication between pods just like docker you can use the service name
    // in our case it's the auth-api-service than "." than the namespace used, in our case it's the default
    // Use kubectl get namespace to see all the namespaces
    const hashedPW = await axios.get(`http://${process.env.AUTH_API}/hashed-password/` + password);
    // since it's a dummy service, we don't really care for the hashed-pw either
    console.log(hashedPW, email);
    res.status(201).json({ message: 'User created!' });
  } catch (err) {
    console.log(err);
    return res
      .status(500)
      .json({ message: 'Creating the user failed - please try again later.' });
  }
});

app.post('/login', async (req, res) => {
  // It's just a dummy service - we don't really care for the email
  const email = req.body.email;
  const password = req.body.password;

  if (!password || password.trim().length === 0 || !email || email.trim().length === 0) {
    return res
      .status(422)
      .json({ message: 'An email and password needs to be specified!' });
  }

  // normally, we'd find a user by email and grab his/ her ID and hashed password
  const hashedPassword = password + '_hash';
  /* ---- Second approach ---*/
  // AUTH_API_SERVICE_SERVICE_HOST is an environment variable auto generated by kubernetes when you apply your service.yml file
  // For example the auth-api-service
  // The environment variable must be the name of the service all caps with "-" replaced by "_" and add SERVICE_HOST at the end
  const response = await axios.get(
    `http://${process.env.AUTH_API_SERVICE_SERVICE_HOST}/token/` + hashedPassword + '/' + password
  );

  if (response.status === 200) {
    return res.status(200).json({ token: response.data.token });
  }
  return res.status(response.status).json({ message: 'Logging in failed!' });
});

app.listen(8080);
